# RÃ©gles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_back_admin_youtube:
    path:     /youtube/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Admin:youtube, id: null }

muzikspirit_back_admin_dailymotion:
    path:     /dailymotion/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Admin:dailymotion, id: null }

muzikspirit_back_admin_vimeo:
    path:     /vimeo/{id}
    defaults: { _controller: MuzikSpiritBackBundle:Admin:vimeo, id: null }

muzikspirit_back_admin_preview:
    path:     /preview
    defaults: { _controller: MuzikSpiritBackBundle:Admin:preview }

muzikspirit_back_admin_sameartiste:
    path:     /same-artiste/{type}
    defaults: { _controller: MuzikSpiritBackBundle:Admin:sameartiste, type: news }

muzikspirit_back_admin_getimage:
    path:     /get-image/{type}
    defaults: { _controller: MuzikSpiritBackBundle:Admin:getimage, type: 1 }