# RÃ©gles config routage
#
# Nom de la route :
# nom_de_l_app_bundle_classe_action
#
# Appel Controleur
# NomduBundle:NomducControleur:Nom de L'action
#
# Ordre de configuration :
# Route -> Controleur -> Vue

muzikspirit_front_lyrics_list:
    path:     /lyrics/list/{section}/{page}
    defaults: { _controller: MuzikSpiritFrontBundle:Lyrics:list, section : all, page : 1 }

muzikspirit_front_lyrics_view:
    path:     /lyrics/{slug}/{id}
    defaults: { _controller: MuzikSpiritFrontBundle:Lyrics:view, page : 1 }
    requirements:
      id: \d+
      _method: GET